name: maring
description: Discover Top Podcasts & Music | Your Ultimate Audio Hub For Your Pods!

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  chewie:
    path: packages/chewie/
  vimeo_video_player:
    path: packages/vimeo/

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.0
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  fluttertoast: ^8.0.9
  flutter_rating_bar: ^4.0.1
  progress_dialog_null_safe: ^1.0.7
  pinput: ^2.2.31
  readmore: ^2.2.0
  visibility_detector: ^0.4.0+2
  flutter_inappwebview: ^5.8.0
  flutter_switch: ^0.3.2
  flutter_locales: ^3.0.1
  intl_phone_field: ^3.1.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  provider: ^6.0.5
  intl: ^0.19.0
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1
  http: ^0.13.5
  google_sign_in: ^6.1.4
  youtube_player_flutter: ^8.1.2
  cloud_firestore: ^4.8.4
  carousel_slider: ^4.2.1
  responsive_grid_list: ^1.3.2
  percent_indicator: ^4.2.3
  sign_in_with_apple: ^5.0.0
  onesignal_flutter: ^5.0.4
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  firebase_messaging: ^14.7.3
  # Players
  youtube_player_iframe: ^4.0.4
  video_player: ^2.7.0
  video_player_web_hls: ^1.0.0+3
  subtitle_wrapper_package: ^2.1.1
  # Audio Player
  just_audio: ^0.9.31
  audio_session: ^0.1.11
  rxdart: ^0.27.7
  just_audio_mpv: ^0.1.6
  just_audio_windows: ^0.2.0
  audio_video_progress_bar: ^0.9.0
  just_audio_background: ^0.0.1-beta.11
  miniplayer: ^1.0.1
  async: ^2.5.0
  # Audio Player
  scrollview_observer: ^1.14.0
  expandable_text: ^2.3.0
  # Payment Gateways
  in_app_purchase: ^3.1.5
  in_app_purchase_storekit: ^0.3.6+1
  in_app_purchase_android: ^0.3.0+11
  razorpay_web: ^1.3.5
  paytm_allinonesdk: ^1.2.1
  flutter_stripe: ^9.2.2
  flutter_dotenv: ^5.1.0
  http_auth: ^1.0.2
  flutter_paypal: ^0.2.0
  flutterwave_standard: ^1.0.4
  uuid: ^4.0.0
  payu_checkoutpro_flutter: ^1.0.4
  pay_with_paystack: ^1.0.6
  flutter_share: ^2.0.0
  # Payment Gateways
  marquee: ^2.2.3
  # Upload Reels
  ffmpeg_kit_flutter_min: ^6.0.3
  video_thumbnail: ^0.5.3
  gallery_saver: ^2.3.2
  detectable_text_field: ^2.1.0
  audioplayers: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  camera: ^0.10.5+7
  countdown_progress_indicator: ^0.1.2
  email_validator: ^2.1.17
  google_mobile_ads: ^4.0.0
  image_picker: ^1.0.7
 

# dependency_overrides:
#   webview_flutter_wkwebview: ^3.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/
    - assets/locales/en.json
    - assets/locales/hi.json
    - assets/locales/af.json
    - assets/locales/ar.json
    - assets/locales/de.json
    - assets/locales/es.json
    - assets/locales/fr.json
    - assets/locales/gu.json
    - assets/locales/id.json
    - assets/locales/nl.json
    - assets/locales/pt.json
    - assets/locales/sq.json
    - assets/locales/tr.json
    - assets/locales/vi.json
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
