// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_dEUy7YvU8wyxt1yAS-37Jb_W6g1k3_s',
    appId: '1:392636948938:android:d6848bffcf8268d8246f33',
    messagingSenderId: '392636948938',
    projectId: 'maring-d2350',
    storageBucket: 'maring-d2350.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDksEP6Doik_8JtZOiDAzTYPw2f0jyboQ4',
    appId: '1:392636948938:ios:4c680c51161007cc246f33',
    messagingSenderId: '392636948938',
    projectId: 'maring-d2350',
    storageBucket: 'maring-d2350.appspot.com',
    //androidClientId: '997133946428-171bm07artqpela0a6718rsdipuhvvqs.apps.googleusercontent.com',
    //iosClientId: '997133946428-euu7a1ravjqb4kp1oauh7heq6ison2fc.apps.googleusercontent.com',
    iosBundleId: 'com.marina.sharing',
  );
}
